baseurl: /
url: https://convia.org/

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Convia
full_title: Convia Foundation
show_downloads: false
description: Software Foundation 

logo: https://res.cloudinary.com/subscribility-p/image/upload/w_250/cdn/qr.a3c2.com/logo.png

github:
  is_project_page: false
  show_hosted: false

plugins:
  - jekyll-relative-links

markdown: 
  - CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - RELEASES.md